#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O -J $PROXY $1; cd -
}

#VERSION=$(gh_releases invoiceninja/invoiceninja | grep 'release$' | sort -V | tail -1)
#URL="https://github.com/invoiceninja/invoiceninja/releases/download/$VERSION/invoiceninja.zip"
#
# Currently above downloads latest release; however v5 is still beta (but not in name...)
# This URL will auto download latest stable:
URL=https://github.com/invoiceninja/invoiceninja/releases/download/v5.5.18/invoiceninja.zip
SRC=/usr/local/src

dl $URL $SRC #/invoiceninja.zip
