#!/bin/bash -ex

DB_NAME=ninja
DB_USER=ninja
DB_PASS=$(mcookie)

ADMIN_MAIL="admin%40example.com" # '@' encoded = '%40'
ADMIN_PASS=turnkey1

SRC=/usr/local/src
WEBROOT=/var/www/invoiceninja
CONF=$WEBROOT/config/configuration.php

LOC_SHARE=/usr/local/share
LOC_BIN=/usr/local/bin

# install PhantomJS locally
tar xf $SRC/phantomjs-*-linux-x86_64.tar.bz2 -C $LOC_SHARE
cat > $LOC_BIN/phantomjs <<EOF
#!/bin/sh -e

# Wrapper script to work around PhantomJS bug with Buster OpenSSL;
# e.g.: https://github.com/bazelbuild/rules_closure/issues/351

export OPENSSL_CONF=/etc/ssl
$LOC_SHARE/phantomjs-*-linux-x86_64/bin/phantomjs "\$@"
EOF
chmod +x $LOC_BIN/phantomjs
rm $SRC/phantomjs-*-linux-x86_64.tar.bz2

# install Invoice Ninja
mkdir -p $WEBROOT
unzip $SRC/invoiceninja.zip -d $WEBROOT/
rm -f $SRC/invoiceninja.zip
cp $(dirname $CONF)/configuration.sample.php $CONF
chown -R www-data:www-data $WEBROOT

service mysql start

mysqladmin create $DB_NAME
mysql --batch --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

sed -i "\|\$sitename =|s|=.*|= \"TurnKey Invoice Ninja\";|" $CONF
sed -i "\|\$dbUser=|s|=.*|=\"$DB_USER\";|" $CONF
sed -i "\|\$dbPassword=|s|=.*|=\"$DB_PASS\";|" $CONF
sed -i "\|\$dbDatabase=|s|=.*|=\"$DB_NAME\";|" $CONF
sed -i "\|\$sessionpassword =|s|=.*|=\"$(mcookie)($mcookie)\";|" $CONF

a2dissite 000-default
a2ensite invoiceninja
a2enmod rewrite

exit 1
service apache2 start

CURL="curl -c /tmp/cookie -b /tmp/cookie"
$CURL localhost/install\ \
  --data-raw "email=$ADMIN_MAIL&password=$ADMIN_PASS&firstname=Admin&lastname=User&company=TurnKey&install=Install"

service mysql stop
service apache2 stop
