#!/bin/bash -e
# regenerate invoice ninja secrets and mysql user password

. /etc/default/inithooks

CONF=/var/www/invoiceninja/.env

DB_USER=ninja
DB_PASS=$(mcookie)

sed -i "\|DB_PASSWORD=|s|=.*|=$DB_PASS|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user="$DB_USER" --pass="$DB_PASS"

sed -i "\|API_SECRET=|s|=.*|=$(mcookie)$(mcookie)|" $CONF
sed -i "\|UPDATE_SECRET=|s|=.*|=$(mcookie)|" $CONF

turnkey-artisan config:cache
turnkey-artisan key:generate --force
turnkey-artisan config:clear
