#!/bin/bash -e
# set invoice ninja admin password & email

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

printf '%s\n' "$APP_PASS" | \
    $INITHOOKS_PATH/bin/invoice-ninja.py --pass-stdin \
        --email="$APP_EMAIL" --domain="$APP_DOMAIN"
